USE `cardiology-auth`;

CREATE TABLE IF NOT EXISTS user (
  id BIGINT NOT NULL AUTO_INCREMENT,
  phone VARCHAR(32) DEFAULT NULL COMMENT '手机号',
  qq_openid VARCHAR(64) DEFAULT NULL COMMENT 'QQ OpenID',
  github_id VARCHAR(64) DEFAULT NULL COMMENT 'GitHub ID',
  guest_id VARCHAR(128) DEFAULT NULL COMMENT '游客 ID',
  nickname VARCHAR(64) DEFAULT NULL COMMENT '昵称',
  avatar VARCHAR(512) DEFAULT NULL COMMENT '头像 URL',
  status INT NOT NULL DEFAULT 1 COMMENT '1=正常',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  last_login_at DATETIME DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_user_phone (phone),
  KEY idx_user_guest_id (guest_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
